version: "3.0"
services:
  back:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./back:/var/www
    working_dir: /var/www
    depends_on:
      - mysql-server
  front:
    image: node:lts-alpine3.14
    volumes:
      - ./front:/app
    working_dir: /app
    tty: true
    command: sh -c 
      "npm install &&
       npm run build
       "
  mysql-server:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    entrypoint: "bash -c 'echo -e \"CREATE DATABASE IF NOT EXISTS musicup;\" > /docker-entrypoint-initdb.d/musicup.sql &&
                          /entrypoint.sh mysqld'"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - back
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./front:/sites/rosbuket
      - ./back:/var/www/
volumes:
  mysqldata:
    driver: local